Repository kusitms-dear-k/DEAR.K_BE, pull requests merged in 2025-05, with the labels that each got.

#32 [FEAT] 프로필 등록 기능
  src/main/java/com/deark/be/auth/dto/response/LoginResponse.java
  src/main/java/com/deark/be/user/controller/UserController.java
  src/main/java/com/deark/be/user/domain/User.java
  src/main/java/com/deark/be/user/domain/type/Gender.java
  src/main/java/com/deark/be/user/dto/request/SaveProfileRequest.java
  src/main/java/com/deark/be/user/dto/request/UserRequest.java
  src/main/java/com/deark/be/user/dto/response/UserResponse.java
  src/main/java/com/deark/be/user/repository/UserRepository.java
  src/main/java/com/deark/be/user/service/UserService.java
Labels: 📬 API, ✨ Feature

#34 [FEAT] 디자인 상세 조회
  src/main/java/com/deark/be/design/controller/DesignController.java
  src/main/java/com/deark/be/design/domain/Design.java
  src/main/java/com/deark/be/design/dto/response/DesignDetailResponse.java
  src/main/java/com/deark/be/design/dto/response/StoreDesignResponse.java
  src/main/java/com/deark/be/design/dto/response/StoreDesignResponseList.java
  src/main/java/com/deark/be/design/exception/errorcode/DesignErrorCode.java
  src/main/java/com/deark/be/design/repository/DesignRepository.java
  src/main/java/com/deark/be/design/repository/DesignRepositoryCustom.java
  src/main/java/com/deark/be/design/repository/DesignRepositoryImpl.java
  src/main/java/com/deark/be/design/repository/init/CreamInitializer.java
  src/main/java/com/deark/be/design/repository/init/SheetInitializer.java
  src/main/java/com/deark/be/design/repository/init/SizeInitializer.java
  src/main/java/com/deark/be/design/service/DesignService.java
Labels: 📬 API, ✨ Feature

#39 [REFACTOR] 통합 검색 수정
  src/main/java/com/deark/be/design/controller/DesignController.java
  src/main/java/com/deark/be/design/repository/DesignRepositoryCustom.java
  src/main/java/com/deark/be/design/repository/DesignRepositoryImpl.java
  src/main/java/com/deark/be/design/service/DesignService.java
  src/main/java/com/deark/be/store/controller/StoreController.java
  src/main/java/com/deark/be/store/repository/StoreRepositoryCustom.java
  src/main/java/com/deark/be/store/repository/StoreRepositoryImpl.java
  src/main/java/com/deark/be/store/repository/init/StoreInitializer.java
  src/main/java/com/deark/be/store/service/StoreService.java
Labels: 🔨 Refactor

#43 [REFACTOR] 내 요청서 관련 수정
  src/main/java/com/deark/be/design/dto/response/SearchDesignResponse.java
  src/main/java/com/deark/be/design/repository/DesignRepositoryImpl.java
  src/main/java/com/deark/be/order/controller/MypageController.java
  src/main/java/com/deark/be/order/dto/response/MyOrderStatusResponse.java
  src/main/java/com/deark/be/order/dto/response/QAStatusResponse.java
  src/main/java/com/deark/be/order/service/OrderService.java
Labels: 🔨 Refactor

#49 [FEAT] 가게별 디자인목록 조회 API + 주문서 생성 로직 수정
  src/main/java/com/deark/be/design/controller/DesignController.java
  src/main/java/com/deark/be/design/dto/response/StoreDesignSimpleResponse.java
  src/main/java/com/deark/be/design/repository/DesignRepository.java
  src/main/java/com/deark/be/design/service/DesignService.java
  src/main/java/com/deark/be/order/controller/OrderController.java
  src/main/java/com/deark/be/order/dto/request/SubmitOrderRequest.java
  src/main/java/com/deark/be/order/service/OrderService.java
Labels: 📬 API

#50 [FEAT] 주문서 작성에 필요한 기능
  src/main/java/com/deark/be/design/domain/Cream.java
  src/main/java/com/deark/be/design/domain/Sheet.java
  src/main/java/com/deark/be/design/domain/Size.java
  src/main/java/com/deark/be/design/service/DesignService.java
  src/main/java/com/deark/be/order/controller/MypageController.java
  src/main/java/com/deark/be/order/controller/OrderController.java
  src/main/java/com/deark/be/order/dto/response/BusinessHoursResponse.java
  src/main/java/com/deark/be/order/dto/response/MyOrderDetailResponse.java
  src/main/java/com/deark/be/order/dto/response/PickUpDateResponse.java
  src/main/java/com/deark/be/order/dto/response/PickUpDateResponseList.java
  src/main/java/com/deark/be/order/dto/response/QAResponse.java
  src/main/java/com/deark/be/order/repository/init/CommonQuestionInitializer.java
  src/main/java/com/deark/be/order/repository/init/MessageInitializer.java
  src/main/java/com/deark/be/order/repository/init/QAInitializer.java
  src/main/java/com/deark/be/order/service/MypageService.java
  src/main/java/com/deark/be/order/service/OrderService.java
  src/main/java/com/deark/be/store/domain/Store.java
  src/main/java/com/deark/be/store/dto/response/DesignCreamResponse.java
  src/main/java/com/deark/be/store/dto/response/DesignCreamResponseList.java
  src/main/java/com/deark/be/store/dto/response/DesignSheetResponse.java
  src/main/java/com/deark/be/store/dto/response/DesignSheetResponseList.java
  src/main/java/com/deark/be/store/dto/response/DesignSizeResponse.java
  src/main/java/com/deark/be/store/dto/response/DesignSizeResponseList.java
  src/main/java/com/deark/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/deark/be/store/repository/BusinessHoursRepository.java
  src/main/java/com/deark/be/store/service/BusinessHoursService.java
  src/main/java/com/deark/be/store/service/StoreService.java
Labels: 📬 API, ✨ Feature

#55 [FEAT] 마이페이지 주문 관리 탭 관련 api 구현
  src/main/java/com/deark/be/order/controller/MypageController.java
  src/main/java/com/deark/be/order/domain/Message.java
  src/main/java/com/deark/be/order/domain/QA.java
  src/main/java/com/deark/be/order/domain/type/ProgressStatus.java
  src/main/java/com/deark/be/order/dto/response/OrderManagementResponse.java
  src/main/java/com/deark/be/order/dto/response/OrderManagementResponseList.java
  src/main/java/com/deark/be/order/repository/MessageRepository.java
  src/main/java/com/deark/be/order/repository/MessageRepositoryCustom.java
  src/main/java/com/deark/be/order/repository/MessageRepositoryImpl.java
  src/main/java/com/deark/be/order/repository/init/CommonQuestionInitializer.java
  src/main/java/com/deark/be/order/repository/init/MessageInitializer.java
  src/main/java/com/deark/be/order/repository/init/QAInitializer.java
  src/main/java/com/deark/be/order/service/MypageService.java
  src/main/java/com/deark/be/order/service/OrderService.java
Labels: 📬 API, ✨ Feature

#57 [FEAT] 이벤트 메모 작성 api 구현
  src/main/java/com/deark/be/event/controller/EventController.java
  src/main/java/com/deark/be/event/domain/EventDesign.java
  src/main/java/com/deark/be/event/domain/EventStore.java
  src/main/java/com/deark/be/event/dto/request/UpdateMemoRequest.java
  src/main/java/com/deark/be/event/dto/response/StoreInEventResponse.java
  src/main/java/com/deark/be/event/repository/EventStoreRepository.java
  src/main/java/com/deark/be/event/repository/EventStoreRepositoryCustom.java
  src/main/java/com/deark/be/event/repository/EventStoreRepositoryImpl.java
  src/main/java/com/deark/be/event/repository/init/EventDesignInitializer.java
  src/main/java/com/deark/be/event/service/EventDesignService.java
  src/main/java/com/deark/be/event/service/EventService.java
  src/main/java/com/deark/be/event/service/EventStoreService.java
Labels: 📬 API, ✨ Feature

#66 [FEAT] 마이페이지 메인 화면 - 가장 다가오는 이벤트 조회 api
  src/main/java/com/deark/be/event/dto/response/DesignInEventResponse.java
  src/main/java/com/deark/be/event/dto/response/EventResponse.java
  src/main/java/com/deark/be/event/repository/EventRepository.java
  src/main/java/com/deark/be/event/repository/EventRepositoryCustom.java
  src/main/java/com/deark/be/event/repository/EventRepositoryImpl.java
  src/main/java/com/deark/be/event/service/EventService.java
  src/main/java/com/deark/be/order/controller/MypageController.java
  src/main/java/com/deark/be/order/dto/response/UpcomingEventResponse.java
  src/main/java/com/deark/be/order/service/MypageService.java
Labels: 📬 API, ✨ Feature
